//As generated by your Gather Account. Should be in a .env file, but this can work too.
export const API_KEY = "";

//This should be the full URL, not just the spaceId\\spaceName
export const SPACE_URLS = [
  "{YOUR SPACE URL HERE}",
];
